# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "2ceda623-886f-440b-8ab7-52603f6693f2",
# META       "default_lakehouse_name": "lakehouse2",
# META       "default_lakehouse_workspace_id": "7922d782-0fd2-4ace-b504-d02b210dc1dd",
# META       "known_lakehouses": [
# META         {
# META           "id": "2ceda623-886f-440b-8ab7-52603f6693f2"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

# Welcome to your new notebook
# Type here in the cell editor to add code!


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%pyspark
# MAGIC df = spark.sql("SELECT * FROM lakehouse2.dbo.Date LIMIT 1000")
# MAGIC display(df)
# MAGIC df.describe().show()


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df.describe("DayOfMonth").show()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%pyspark
# MAGIC df = spark.sql("SELECT * FROM lakehouse2.dbo.Date LIMIT 1000")
# MAGIC display(df)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for PySpark DataFrame

def clean_data(df):
    # Filter rows based on column: 'DayOfYear'
    df = df.filter(df['DayOfYear'] == "186")
    return df

df_clean = clean_data(df)
display(df_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************


from matplotlib import pyplot as plt


data = spark.sql("SELECT * FROM lakehouse2.dbo.Date LIMIT 1000")

# Clear the plot area
plt.clf()

# Create a Figure
fig = plt.figure(figsize=(12,8))

# Create a bar plot of product counts by category
plt.bar(x=data['DayofWeek'], height=data['DayOfQuarter'], color='orange')

# Customize the chart
plt.title('Test title')
plt.xlabel('DayNameLabel')
plt.ylabel('DayOfWeekLabel')
plt.grid(color='#95a5a6', linestyle='--', linewidth=2, axis='y', alpha=0.7)
plt.xticks(rotation=70)

# Show the plot area
plt.show()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

#The End


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

